version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: jobtracker-db
    environment:
      POSTGRES_USER: jobtracker_user
      POSTGRES_PASSWORD: jobtracker_pass
      POSTGRES_DB: jobtracker_db
    ports:
      - "5432:5432"
    volumes:
      - jobtracker-data:/var/lib/postgresql/data

volumes:
  jobtracker-data: